/*
 * File:           C:\Users\jberlin\OneDrive - Analog Devices, Inc\SigmaDSP with Microcontrollers\SIMPLE SigmaDSP Teensy Project\lib\SigmaStudio\Simple_SS_Project_145x_146x_INDIRECT_ACCESS_TABLE_IC_1_PARAM.h
 *
 * Created:        Monday, April 6, 2020 3:26:13 PM
 * Description:    Simple_SS_Project_145x_146x_INDIRECT_ACCESS_TABLE:IC 1 parameter RAM definitions.
 *
 * This software is distributed in the hope that it will be useful,
 * but is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
 * CONDITIONS OF ANY KIND, without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 * This software may only be used to program products purchased from
 * Analog Devices for incorporation by you into audio products that
 * are intended for resale to audio product end users. This software
 * may not be distributed whole or in any part to third parties.
 *
 * Copyright ©2020 Analog Devices, Inc. All rights reserved.
 */
#ifndef __SIMPLE_SS_PROJECT_145X_146X_INDIRECT_ACCESS_TABLE_IC_1_PARAM_H__
#define __SIMPLE_SS_PROJECT_145X_146X_INDIRECT_ACCESS_TABLE_IC_1_PARAM_H__


/* Module SafeLoadModule - SafeLoadModule*/
#define MOD_SAFELOADMODULE_COUNT                       14
#define MOD_SAFELOADMODULE_DEVICE                      "IC1"
#define MOD_SAFELOADMODULE_DATA_SAFELOAD0_ADDR         24576
#define MOD_SAFELOADMODULE_DATA_SAFELOAD0_MEMORYPAGE   0
#define MOD_SAFELOADMODULE_DATA_SAFELOAD1_ADDR         24577
#define MOD_SAFELOADMODULE_DATA_SAFELOAD1_MEMORYPAGE   0
#define MOD_SAFELOADMODULE_DATA_SAFELOAD2_ADDR         24578
#define MOD_SAFELOADMODULE_DATA_SAFELOAD2_MEMORYPAGE   0
#define MOD_SAFELOADMODULE_DATA_SAFELOAD3_ADDR         24579
#define MOD_SAFELOADMODULE_DATA_SAFELOAD3_MEMORYPAGE   0
#define MOD_SAFELOADMODULE_DATA_SAFELOAD4_ADDR         24580
#define MOD_SAFELOADMODULE_DATA_SAFELOAD4_MEMORYPAGE   0
#define MOD_SAFELOADMODULE_ADDRESS_SAFELOAD_ADDR       24581
#define MOD_SAFELOADMODULE_ADDRESS_SAFELOAD_MEMORYPAGE 0
#define MOD_SAFELOADMODULE_NUM_SAFELOAD_LOWER_ADDR     24582
#define MOD_SAFELOADMODULE_NUM_SAFELOAD_LOWER_MEMORYPAGE 0
#define MOD_SAFELOADMODULE_NUM_SAFELOAD_UPPER_ADDR     24583
#define MOD_SAFELOADMODULE_NUM_SAFELOAD_UPPER_MEMORYPAGE 0

/* Module FrameWork - FrameWork*/
#define MOD_FRAMEWORK_COUNT                            4
#define MOD_FRAMEWORK_DEVICE                           "IC1"
#define MOD_FRAMEWORK_PMCHECKSUM_ADDR                  30
#define MOD_FRAMEWORK_PMCHECKSUM_FIXPT                 0x00000000
#define MOD_FRAMEWORK_PMCHECKSUM_VALUE                 SIGMASTUDIOTYPE_INTEGER_CONVERT(0)
#define MOD_FRAMEWORK_PMCHECKSUM_TYPE                  SIGMASTUDIOTYPE_INTEGER
#define MOD_FRAMEWORK_PMCHECKSUM_MEMORYPAGE            0
#define MOD_FRAMEWORK_DM0CHECKSUM_ADDR                 31
#define MOD_FRAMEWORK_DM0CHECKSUM_FIXPT                0x00000000
#define MOD_FRAMEWORK_DM0CHECKSUM_VALUE                SIGMASTUDIOTYPE_INTEGER_CONVERT(0)
#define MOD_FRAMEWORK_DM0CHECKSUM_TYPE                 SIGMASTUDIOTYPE_INTEGER
#define MOD_FRAMEWORK_DM0CHECKSUM_MEMORYPAGE           0
#define MOD_FRAMEWORK_DM1CHECKSUM_ADDR                 32
#define MOD_FRAMEWORK_DM1CHECKSUM_FIXPT                0x00000000
#define MOD_FRAMEWORK_DM1CHECKSUM_VALUE                SIGMASTUDIOTYPE_INTEGER_CONVERT(0)
#define MOD_FRAMEWORK_DM1CHECKSUM_TYPE                 SIGMASTUDIOTYPE_INTEGER
#define MOD_FRAMEWORK_DM1CHECKSUM_MEMORYPAGE           0
#define MOD_FRAMEWORK_CHECKSUMCALCULATIONDONE_ADDR     33
#define MOD_FRAMEWORK_CHECKSUMCALCULATIONDONE_FIXPT    0x00000000
#define MOD_FRAMEWORK_CHECKSUMCALCULATIONDONE_VALUE    SIGMASTUDIOTYPE_INTEGER_CONVERT(0)
#define MOD_FRAMEWORK_CHECKSUMCALCULATIONDONE_TYPE     SIGMASTUDIOTYPE_INTEGER
#define MOD_FRAMEWORK_CHECKSUMCALCULATIONDONE_MEMORYPAGE 0

/* Module LED_Pulse - Pulse with dynamic duty cycle*/
#define MOD_LED_PULSE_COUNT                            4
#define MOD_LED_PULSE_DEVICE                           "IC1"
#define MOD_LED_PULSE_ALG0_ISROUNDED_ADDR              34
#define MOD_LED_PULSE_ALG0_ISROUNDED_VALUE             SIGMASTUDIOTYPE_8_24_CONVERT(0)
#define MOD_LED_PULSE_ALG0_ISROUNDED_TYPE              SIGMASTUDIOTYPE_8_24
#define MOD_LED_PULSE_ALG0_ISROUNDED_MEMORYPAGE        0
#define MOD_LED_PULSE_ALG0_FREQ_STEP_ADDR              35
#define MOD_LED_PULSE_ALG0_FREQ_STEP_VALUE             SIGMASTUDIOTYPE_8_24_CONVERT(2.08333333333333E-05)
#define MOD_LED_PULSE_ALG0_FREQ_STEP_TYPE              SIGMASTUDIOTYPE_8_24
#define MOD_LED_PULSE_ALG0_FREQ_STEP_MEMORYPAGE        0
#define MOD_LED_PULSE_ALG0_ON_ADDR                     36
#define MOD_LED_PULSE_ALG0_ON_VALUE                    SIGMASTUDIOTYPE_8_24_CONVERT(1)
#define MOD_LED_PULSE_ALG0_ON_TYPE                     SIGMASTUDIOTYPE_8_24
#define MOD_LED_PULSE_ALG0_ON_MEMORYPAGE               0
#define MOD_LED_PULSE_ALG0_TH_ADDR                     37
#define MOD_LED_PULSE_ALG0_TH_VALUE                    SIGMASTUDIOTYPE_8_24_CONVERT(0.5)
#define MOD_LED_PULSE_ALG0_TH_TYPE                     SIGMASTUDIOTYPE_8_24
#define MOD_LED_PULSE_ALG0_TH_MEMORYPAGE               0

/* Module Single_Volume - Single Volume*/
#define MOD_SINGLE_VOLUME_COUNT                        2
#define MOD_SINGLE_VOLUME_DEVICE                       "IC1"
#define MOD_SINGLE_VOLUME_ALG0_TARGET_ADDR             39
#define MOD_SINGLE_VOLUME_ALG0_TARGET_VALUE            SIGMASTUDIOTYPE_8_24_CONVERT(1)
#define MOD_SINGLE_VOLUME_ALG0_TARGET_TYPE             SIGMASTUDIOTYPE_8_24
#define MOD_SINGLE_VOLUME_ALG0_TARGET_MEMORYPAGE       0
#define MOD_SINGLE_VOLUME_ALG0_SLEW_MODE_ADDR          40
#define MOD_SINGLE_VOLUME_ALG0_SLEW_MODE_FIXPT         0x0000208A
#define MOD_SINGLE_VOLUME_ALG0_SLEW_MODE_VALUE         SIGMASTUDIOTYPE_INTEGER_CONVERT(8330)
#define MOD_SINGLE_VOLUME_ALG0_SLEW_MODE_TYPE          SIGMASTUDIOTYPE_INTEGER
#define MOD_SINGLE_VOLUME_ALG0_SLEW_MODE_MEMORYPAGE    0

/* Module Left_Filter - General Eq (2nd order)*/
#define MOD_LEFT_FILTER_COUNT                          6
#define MOD_LEFT_FILTER_DEVICE                         "IC1"
#define MOD_LEFT_FILTER_ALG0_SLEWMODE_ADDR             46
#define MOD_LEFT_FILTER_ALG0_SLEWMODE_FIXPT            0x0000208A
#define MOD_LEFT_FILTER_ALG0_SLEWMODE_VALUE            SIGMASTUDIOTYPE_INTEGER_CONVERT(8330)
#define MOD_LEFT_FILTER_ALG0_SLEWMODE_TYPE             SIGMASTUDIOTYPE_INTEGER
#define MOD_LEFT_FILTER_ALG0_SLEWMODE_MEMORYPAGE       0
#define MOD_LEFT_FILTER_ALG0_EQS300MULTIDPHWSLEWP1ALG1TARGB210_ADDR 24603
#define MOD_LEFT_FILTER_ALG0_EQS300MULTIDPHWSLEWP1ALG1TARGB210_VALUE SIGMASTUDIOTYPE_8_24_CONVERT(0.27603951961991)
#define MOD_LEFT_FILTER_ALG0_EQS300MULTIDPHWSLEWP1ALG1TARGB210_TYPE SIGMASTUDIOTYPE_8_24
#define MOD_LEFT_FILTER_ALG0_EQS300MULTIDPHWSLEWP1ALG1TARGB210_MEMORYPAGE 0
#define MOD_LEFT_FILTER_ALG0_EQS300MULTIDPHWSLEWP1ALG1TARGB211_ADDR 24604
#define MOD_LEFT_FILTER_ALG0_EQS300MULTIDPHWSLEWP1ALG1TARGB211_VALUE SIGMASTUDIOTYPE_8_24_CONVERT(0.55207903923982)
#define MOD_LEFT_FILTER_ALG0_EQS300MULTIDPHWSLEWP1ALG1TARGB211_TYPE SIGMASTUDIOTYPE_8_24
#define MOD_LEFT_FILTER_ALG0_EQS300MULTIDPHWSLEWP1ALG1TARGB211_MEMORYPAGE 0
#define MOD_LEFT_FILTER_ALG0_EQS300MULTIDPHWSLEWP1ALG1TARGB212_ADDR 24605
#define MOD_LEFT_FILTER_ALG0_EQS300MULTIDPHWSLEWP1ALG1TARGB212_VALUE SIGMASTUDIOTYPE_8_24_CONVERT(0.27603951961991)
#define MOD_LEFT_FILTER_ALG0_EQS300MULTIDPHWSLEWP1ALG1TARGB212_TYPE SIGMASTUDIOTYPE_8_24
#define MOD_LEFT_FILTER_ALG0_EQS300MULTIDPHWSLEWP1ALG1TARGB212_MEMORYPAGE 0
#define MOD_LEFT_FILTER_ALG0_EQS300MULTIDPHWSLEWP1ALG1TARGB213_ADDR 24606
#define MOD_LEFT_FILTER_ALG0_EQS300MULTIDPHWSLEWP1ALG1TARGB213_VALUE SIGMASTUDIOTYPE_8_24_CONVERT(-0.489728076772249)
#define MOD_LEFT_FILTER_ALG0_EQS300MULTIDPHWSLEWP1ALG1TARGB213_TYPE SIGMASTUDIOTYPE_8_24
#define MOD_LEFT_FILTER_ALG0_EQS300MULTIDPHWSLEWP1ALG1TARGB213_MEMORYPAGE 0
#define MOD_LEFT_FILTER_ALG0_EQS300MULTIDPHWSLEWP1ALG1TARGB214_ADDR 24607
#define MOD_LEFT_FILTER_ALG0_EQS300MULTIDPHWSLEWP1ALG1TARGB214_VALUE SIGMASTUDIOTYPE_8_24_CONVERT(0.385569998292608)
#define MOD_LEFT_FILTER_ALG0_EQS300MULTIDPHWSLEWP1ALG1TARGB214_TYPE SIGMASTUDIOTYPE_8_24
#define MOD_LEFT_FILTER_ALG0_EQS300MULTIDPHWSLEWP1ALG1TARGB214_MEMORYPAGE 0

/* Module Right_Filter - General Eq (2nd order)*/
#define MOD_RIGHT_FILTER_COUNT                         6
#define MOD_RIGHT_FILTER_DEVICE                        "IC1"
#define MOD_RIGHT_FILTER_ALG0_SLEWMODE_ADDR            52
#define MOD_RIGHT_FILTER_ALG0_SLEWMODE_FIXPT           0x0000208A
#define MOD_RIGHT_FILTER_ALG0_SLEWMODE_VALUE           SIGMASTUDIOTYPE_INTEGER_CONVERT(8330)
#define MOD_RIGHT_FILTER_ALG0_SLEWMODE_TYPE            SIGMASTUDIOTYPE_INTEGER
#define MOD_RIGHT_FILTER_ALG0_SLEWMODE_MEMORYPAGE      0
#define MOD_RIGHT_FILTER_ALG0_EQS300MULTIDPHWSLEWP1ALG2TARGB210_ADDR 24608
#define MOD_RIGHT_FILTER_ALG0_EQS300MULTIDPHWSLEWP1ALG2TARGB210_VALUE SIGMASTUDIOTYPE_8_24_CONVERT(0.27603951961991)
#define MOD_RIGHT_FILTER_ALG0_EQS300MULTIDPHWSLEWP1ALG2TARGB210_TYPE SIGMASTUDIOTYPE_8_24
#define MOD_RIGHT_FILTER_ALG0_EQS300MULTIDPHWSLEWP1ALG2TARGB210_MEMORYPAGE 0
#define MOD_RIGHT_FILTER_ALG0_EQS300MULTIDPHWSLEWP1ALG2TARGB211_ADDR 24609
#define MOD_RIGHT_FILTER_ALG0_EQS300MULTIDPHWSLEWP1ALG2TARGB211_VALUE SIGMASTUDIOTYPE_8_24_CONVERT(0.55207903923982)
#define MOD_RIGHT_FILTER_ALG0_EQS300MULTIDPHWSLEWP1ALG2TARGB211_TYPE SIGMASTUDIOTYPE_8_24
#define MOD_RIGHT_FILTER_ALG0_EQS300MULTIDPHWSLEWP1ALG2TARGB211_MEMORYPAGE 0
#define MOD_RIGHT_FILTER_ALG0_EQS300MULTIDPHWSLEWP1ALG2TARGB212_ADDR 24610
#define MOD_RIGHT_FILTER_ALG0_EQS300MULTIDPHWSLEWP1ALG2TARGB212_VALUE SIGMASTUDIOTYPE_8_24_CONVERT(0.27603951961991)
#define MOD_RIGHT_FILTER_ALG0_EQS300MULTIDPHWSLEWP1ALG2TARGB212_TYPE SIGMASTUDIOTYPE_8_24
#define MOD_RIGHT_FILTER_ALG0_EQS300MULTIDPHWSLEWP1ALG2TARGB212_MEMORYPAGE 0
#define MOD_RIGHT_FILTER_ALG0_EQS300MULTIDPHWSLEWP1ALG2TARGB213_ADDR 24611
#define MOD_RIGHT_FILTER_ALG0_EQS300MULTIDPHWSLEWP1ALG2TARGB213_VALUE SIGMASTUDIOTYPE_8_24_CONVERT(-0.489728076772249)
#define MOD_RIGHT_FILTER_ALG0_EQS300MULTIDPHWSLEWP1ALG2TARGB213_TYPE SIGMASTUDIOTYPE_8_24
#define MOD_RIGHT_FILTER_ALG0_EQS300MULTIDPHWSLEWP1ALG2TARGB213_MEMORYPAGE 0
#define MOD_RIGHT_FILTER_ALG0_EQS300MULTIDPHWSLEWP1ALG2TARGB214_ADDR 24612
#define MOD_RIGHT_FILTER_ALG0_EQS300MULTIDPHWSLEWP1ALG2TARGB214_VALUE SIGMASTUDIOTYPE_8_24_CONVERT(0.385569998292608)
#define MOD_RIGHT_FILTER_ALG0_EQS300MULTIDPHWSLEWP1ALG2TARGB214_TYPE SIGMASTUDIOTYPE_8_24
#define MOD_RIGHT_FILTER_ALG0_EQS300MULTIDPHWSLEWP1ALG2TARGB214_MEMORYPAGE 0

/* Module IndirectParamAccessModule - IndirectParamAccessModule*/
#define MOD_INDIRECTPARAMACCESSMODULE_COUNT            17
#define MOD_INDIRECTPARAMACCESSMODULE_DEVICE           "IC1"
#define MOD_INDIRECTPARAMACCESSMODULE_START_ADDRESS_ADDR 24584
#define MOD_INDIRECTPARAMACCESSMODULE_START_ADDRESS_MEMORYPAGE 0
#define MOD_INDIRECTPARAMACCESSMODULE_NUM_OF_LOADS_AND_TRIGGER_ADDR 24585
#define MOD_INDIRECTPARAMACCESSMODULE_NUM_OF_LOADS_AND_TRIGGER_MEMORYPAGE 0
#define MOD_INDIRECTPARAMACCESSMODULE_LEFT_FILTER_TARG_B2_1_ADDR 24586
#define MOD_INDIRECTPARAMACCESSMODULE_LEFT_FILTER_TARG_B2_1_MEMORYPAGE 0
#define MOD_INDIRECTPARAMACCESSMODULE_LEFT_FILTER_TARG_B1_1_ADDR 24587
#define MOD_INDIRECTPARAMACCESSMODULE_LEFT_FILTER_TARG_B1_1_MEMORYPAGE 0
#define MOD_INDIRECTPARAMACCESSMODULE_LEFT_FILTER_TARG_B0_1_ADDR 24588
#define MOD_INDIRECTPARAMACCESSMODULE_LEFT_FILTER_TARG_B0_1_MEMORYPAGE 0
#define MOD_INDIRECTPARAMACCESSMODULE_LEFT_FILTER_TARG_A2_1_ADDR 24589
#define MOD_INDIRECTPARAMACCESSMODULE_LEFT_FILTER_TARG_A2_1_MEMORYPAGE 0
#define MOD_INDIRECTPARAMACCESSMODULE_LEFT_FILTER_TARG_A1_1_ADDR 24590
#define MOD_INDIRECTPARAMACCESSMODULE_LEFT_FILTER_TARG_A1_1_MEMORYPAGE 0
#define MOD_INDIRECTPARAMACCESSMODULE_ADDRESSES0_ADDR  24591
#define MOD_INDIRECTPARAMACCESSMODULE_ADDRESSES0_MEMORYPAGE 0
#define MOD_INDIRECTPARAMACCESSMODULE_ADDRESSES1_ADDR  24592
#define MOD_INDIRECTPARAMACCESSMODULE_ADDRESSES1_MEMORYPAGE 0
#define MOD_INDIRECTPARAMACCESSMODULE_ADDRESSES2_ADDR  24593
#define MOD_INDIRECTPARAMACCESSMODULE_ADDRESSES2_MEMORYPAGE 0
#define MOD_INDIRECTPARAMACCESSMODULE_ADDRESSES3_ADDR  24594
#define MOD_INDIRECTPARAMACCESSMODULE_ADDRESSES3_MEMORYPAGE 0
#define MOD_INDIRECTPARAMACCESSMODULE_ADDRESSES4_ADDR  24595
#define MOD_INDIRECTPARAMACCESSMODULE_ADDRESSES4_MEMORYPAGE 0

#endif
