/*
 * File:           C:\Users\jberlin\OneDrive - Analog Devices, Inc\SigmaDSP with Microcontrollers\SIMPLE SigmaDSP Teensy Project\lib\SigmaStudio\Simple_SS_Project_176x_IC_1_PARAM.h
 *
 * Created:        Wednesday, April 1, 2020 1:54:21 PM
 * Description:    Simple_SS_Project_176x:IC 1 parameter RAM definitions.
 *
 * This software is distributed in the hope that it will be useful,
 * but is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
 * CONDITIONS OF ANY KIND, without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 * This software may only be used to program products purchased from
 * Analog Devices for incorporation by you into audio products that
 * are intended for resale to audio product end users. This software
 * may not be distributed whole or in any part to third parties.
 *
 * Copyright ©2020 Analog Devices, Inc. All rights reserved.
 */
#ifndef __SIMPLE_SS_PROJECT_176X_IC_1_PARAM_H__
#define __SIMPLE_SS_PROJECT_176X_IC_1_PARAM_H__


/* Module Modulo Size - Modulo Size*/
#define MOD_MODULOSIZE_COUNT                           1
#define MOD_MODULOSIZE_DEVICE                          "IC1"
#define MOD_MODULOSIZE_MODULO_SIZE_ADDR                0
#define MOD_MODULOSIZE_MODULO_SIZE_FIXPT               0x00000FFE
#define MOD_MODULOSIZE_MODULO_SIZE_VALUE               SIGMASTUDIOTYPE_INTEGER_CONVERT(4094)
#define MOD_MODULOSIZE_MODULO_SIZE_TYPE                SIGMASTUDIOTYPE_INTEGER

/* Module LED_Pulse - Pulse with dynamic duty cycle*/
#define MOD_LED_PULSE_COUNT                            4
#define MOD_LED_PULSE_DEVICE                           "IC1"
#define MOD_LED_PULSE_ALG0_FREQ_STEP_ADDR              8
#define MOD_LED_PULSE_ALG0_FREQ_STEP_FIXPT             0x000000AE
#define MOD_LED_PULSE_ALG0_FREQ_STEP_VALUE             SIGMASTUDIOTYPE_FIXPOINT_CONVERT(2.08333333333333E-05)
#define MOD_LED_PULSE_ALG0_FREQ_STEP_TYPE              SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LED_PULSE_ALG0_TH_ADDR                     9
#define MOD_LED_PULSE_ALG0_TH_FIXPT                    0x00400000
#define MOD_LED_PULSE_ALG0_TH_VALUE                    SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.5)
#define MOD_LED_PULSE_ALG0_TH_TYPE                     SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LED_PULSE_ALG0_ON_ADDR                     10
#define MOD_LED_PULSE_ALG0_ON_FIXPT                    0x00800000
#define MOD_LED_PULSE_ALG0_ON_VALUE                    SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_LED_PULSE_ALG0_ON_TYPE                     SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LED_PULSE_ALG0_ISROUNDED_ADDR              11
#define MOD_LED_PULSE_ALG0_ISROUNDED_FIXPT             0x00000000
#define MOD_LED_PULSE_ALG0_ISROUNDED_VALUE             SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_LED_PULSE_ALG0_ISROUNDED_TYPE              SIGMASTUDIOTYPE_FIXPOINT

/* Module Single_Volume - Single Volume Shared*/
#define MOD_SINGLE_VOLUME_COUNT                        3
#define MOD_SINGLE_VOLUME_DEVICE                       "IC1"
#define MOD_SINGLE_VOLUME_ALG0_GAINS200ALGGROWDP1GAINTARGET_ADDR 12
#define MOD_SINGLE_VOLUME_ALG0_GAINS200ALGGROWDP1GAINTARGET_FIXPT 0x00800000
#define MOD_SINGLE_VOLUME_ALG0_GAINS200ALGGROWDP1GAINTARGET_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_SINGLE_VOLUME_ALG0_GAINS200ALGGROWDP1GAINTARGET_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_SINGLE_VOLUME_ALG0_GAINS200ALGGROWDP1ALPHA0_ADDR 8190
#define MOD_SINGLE_VOLUME_ALG0_GAINS200ALGGROWDP1ALPHA0_FIXPT 0x007FF259
#define MOD_SINGLE_VOLUME_ALG0_GAINS200ALGGROWDP1ALPHA0_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.999583420126834)
#define MOD_SINGLE_VOLUME_ALG0_GAINS200ALGGROWDP1ALPHA0_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_SINGLE_VOLUME_ALG0_GAINS200ALGGROWDP1ALPHA1_ADDR 8191
#define MOD_SINGLE_VOLUME_ALG0_GAINS200ALGGROWDP1ALPHA1_FIXPT 0x00000DA6
#define MOD_SINGLE_VOLUME_ALG0_GAINS200ALGGROWDP1ALPHA1_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.000416579873166234)
#define MOD_SINGLE_VOLUME_ALG0_GAINS200ALGGROWDP1ALPHA1_TYPE SIGMASTUDIOTYPE_FIXPOINT

/* Module ZeroComp1 - Zero Comparator*/
#define MOD_ZEROCOMP1_COUNT                            1
#define MOD_ZEROCOMP1_DEVICE                           "IC1"
#define MOD_ZEROCOMP1_OUTPUT1_ADDR                     15
#define MOD_ZEROCOMP1_OUTPUT1_FIXPT                    0x00800000
#define MOD_ZEROCOMP1_OUTPUT1_VALUE                    SIGMASTUDIOTYPE_INTEGER_CONVERT(8388608)
#define MOD_ZEROCOMP1_OUTPUT1_TYPE                     SIGMASTUDIOTYPE_INTEGER

/* Module Left_Filter - General (2nd order)*/
#define MOD_LEFT_FILTER_COUNT                          5
#define MOD_LEFT_FILTER_DEVICE                         "IC1"
#define MOD_LEFT_FILTER_ALG0_STAGE0_B0_ADDR            16
#define MOD_LEFT_FILTER_ALG0_STAGE0_B0_FIXPT           0x000085F7
#define MOD_LEFT_FILTER_ALG0_STAGE0_B0_VALUE           SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.0040883370209471)
#define MOD_LEFT_FILTER_ALG0_STAGE0_B0_TYPE            SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LEFT_FILTER_ALG0_STAGE0_B1_ADDR            17
#define MOD_LEFT_FILTER_ALG0_STAGE0_B1_FIXPT           0x00010BEE
#define MOD_LEFT_FILTER_ALG0_STAGE0_B1_VALUE           SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.0081766740418942)
#define MOD_LEFT_FILTER_ALG0_STAGE0_B1_TYPE            SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LEFT_FILTER_ALG0_STAGE0_B2_ADDR            18
#define MOD_LEFT_FILTER_ALG0_STAGE0_B2_FIXPT           0x000085F7
#define MOD_LEFT_FILTER_ALG0_STAGE0_B2_VALUE           SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.0040883370209471)
#define MOD_LEFT_FILTER_ALG0_STAGE0_B2_TYPE            SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LEFT_FILTER_ALG0_STAGE0_A0_ADDR            19
#define MOD_LEFT_FILTER_ALG0_STAGE0_A0_FIXPT           0x00F294EF
#define MOD_LEFT_FILTER_ALG0_STAGE0_A0_VALUE           SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1.8951700997919)
#define MOD_LEFT_FILTER_ALG0_STAGE0_A0_TYPE            SIGMASTUDIOTYPE_FIXPOINT
#define MOD_LEFT_FILTER_ALG0_STAGE0_A1_ADDR            20
#define MOD_LEFT_FILTER_ALG0_STAGE0_A1_FIXPT           0xFF8B5334
#define MOD_LEFT_FILTER_ALG0_STAGE0_A1_VALUE           SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.911523447875689)
#define MOD_LEFT_FILTER_ALG0_STAGE0_A1_TYPE            SIGMASTUDIOTYPE_FIXPOINT

/* Module Right_Filter - General (2nd order)*/
#define MOD_RIGHT_FILTER_COUNT                         5
#define MOD_RIGHT_FILTER_DEVICE                        "IC1"
#define MOD_RIGHT_FILTER_ALG0_STAGE0_B0_ADDR           21
#define MOD_RIGHT_FILTER_ALG0_STAGE0_B0_FIXPT          0x000085F7
#define MOD_RIGHT_FILTER_ALG0_STAGE0_B0_VALUE          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.0040883370209471)
#define MOD_RIGHT_FILTER_ALG0_STAGE0_B0_TYPE           SIGMASTUDIOTYPE_FIXPOINT
#define MOD_RIGHT_FILTER_ALG0_STAGE0_B1_ADDR           22
#define MOD_RIGHT_FILTER_ALG0_STAGE0_B1_FIXPT          0x00010BEE
#define MOD_RIGHT_FILTER_ALG0_STAGE0_B1_VALUE          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.0081766740418942)
#define MOD_RIGHT_FILTER_ALG0_STAGE0_B1_TYPE           SIGMASTUDIOTYPE_FIXPOINT
#define MOD_RIGHT_FILTER_ALG0_STAGE0_B2_ADDR           23
#define MOD_RIGHT_FILTER_ALG0_STAGE0_B2_FIXPT          0x000085F7
#define MOD_RIGHT_FILTER_ALG0_STAGE0_B2_VALUE          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.0040883370209471)
#define MOD_RIGHT_FILTER_ALG0_STAGE0_B2_TYPE           SIGMASTUDIOTYPE_FIXPOINT
#define MOD_RIGHT_FILTER_ALG0_STAGE0_A0_ADDR           24
#define MOD_RIGHT_FILTER_ALG0_STAGE0_A0_FIXPT          0x00F294EF
#define MOD_RIGHT_FILTER_ALG0_STAGE0_A0_VALUE          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1.8951700997919)
#define MOD_RIGHT_FILTER_ALG0_STAGE0_A0_TYPE           SIGMASTUDIOTYPE_FIXPOINT
#define MOD_RIGHT_FILTER_ALG0_STAGE0_A1_ADDR           25
#define MOD_RIGHT_FILTER_ALG0_STAGE0_A1_FIXPT          0xFF8B5334
#define MOD_RIGHT_FILTER_ALG0_STAGE0_A1_VALUE          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.911523447875689)
#define MOD_RIGHT_FILTER_ALG0_STAGE0_A1_TYPE           SIGMASTUDIOTYPE_FIXPOINT

#endif
